version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://toddgoates.com/prod --recursive
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
